import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import ThemeRegistry from "./theme/ThemeRegistry";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Container } from "@mui/material";
import LeftSide from "./components/Sides/LeftSide";
import RightSide from "./components/Sides/RightSide";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <AppRouterCacheProvider>
          <body className={inter.className}>
            {/* <ThemeRegistry> */}
            <Navbar />
            <Container disableGutters maxWidth="xl" sx={{ display: "flex" }}>
              <LeftSide />
              <main>{children}</main>
              <RightSide />
            </Container>
            {/* </ThemeRegistry> */}
          </body>
        </AppRouterCacheProvider>
      </ThemeRegistry>
    </html>
  );
}
